// Build-time codegen: reads the R2 binding -> bucket_name mapping from
// wrangler.jsonc and bakes it into a typed module the Worker can import at
// runtime. The R2 binding object on `env` does NOT expose its underlying
// bucket name, so this generated map is the source of truth for friendly
// labels shown in the UI. Re-run on every build / wrangler dev so the map
// never drifts from wrangler.jsonc.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const WRANGLER_PATH = resolve(ROOT, "wrangler.jsonc");
const OUTPUT_PATH = resolve(ROOT, "src/server/generated/bucketNames.ts");

/** Strip `//` and block comments so JSONC parses as JSON. Ignores `//` inside strings. */
function stripJsonComments(text) {
  let out = "";
  let inString = false;
  let inLineComment = false;
  let inBlockComment = false;

  for (let i = 0; i < text.length; i += 1) {
    const char = text[i];
    const next = text[i + 1];

    if (inLineComment) {
      if (char === "\n") {
        inLineComment = false;
        out += char;
      }
      continue;
    }
    if (inBlockComment) {
      if (char === "*" && next === "/") {
        inBlockComment = false;
        i += 1;
      }
      continue;
    }
    if (inString) {
      out += char;
      if (char === "\\") {
        out += next ?? "";
        i += 1;
      } else if (char === '"') {
        inString = false;
      }
      continue;
    }
    if (char === '"') {
      inString = true;
      out += char;
      continue;
    }
    if (char === "/" && next === "/") {
      inLineComment = true;
      i += 1;
      continue;
    }
    if (char === "/" && next === "*") {
      inBlockComment = true;
      i += 1;
      continue;
    }
    out += char;
  }

  return out;
}

function main() {
  const raw = readFileSync(WRANGLER_PATH, "utf8");
  const config = JSON.parse(stripJsonComments(raw));
  const r2Buckets = Array.isArray(config.r2_buckets) ? config.r2_buckets : [];

  const entries = r2Buckets
    .filter((bucket) => bucket && typeof bucket.binding === "string" && typeof bucket.bucket_name === "string")
    .map((bucket) => [bucket.binding, bucket.bucket_name]);

  const body = entries.map(([binding, name]) => `  ${JSON.stringify(binding)}: ${JSON.stringify(name)},`).join("\n");

  const file = `// AUTO-GENERATED by scripts/generateBucketNames.mjs. Do not edit by hand.
// Maps each R2 binding name to its real bucket_name from wrangler.jsonc.
export const BUCKET_NAMES: Record<string, string> = {
${body}
};
`;

  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, file);
  console.log(`Generated ${entries.length} bucket name mapping(s) -> src/server/generated/bucketNames.ts`);
}

main();
